name: Java bindings tests

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  test-java-bindings:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
      - name: Setup
        run: cd src && make blst && make all
      - name: Test
        run: cd bindings/java && make build test
